# MondoDB connection string (for tool-related data)
mongo_uri_for_tools: mongodb://129.10.187.52:27017/saga_tools

### CA ###
ca:
  # Endpoint where CA hosts relevant files
  endpoint: http://0.0.0.0:8000
  config:
    COUNTRY_NAME: US
    STATE_NAME: MA
    LOCALITY_NAME: Boston
    ORG_NAME: ca
    COMMON_NAME: localhost
    IP: 127.0.0.1

### PROVIDER ###
provider:
  endpoint: https://127.0.0.1:5000
  config:
    COUNTRY_NAME: US
    STATE_NAME: MA
    LOCALITY_NAME: Boston
    ORG_NAME: provider
    COMMON_NAME: 127.0.0.1
    IP: 127.0.0.1

### USER ###
user:
  config:
    COUNTRY_NAME: US
    STATE_NAME: MA
    LOCALITY_NAME: Boston
    ORG_NAME: user
    COMMON_NAME: localhost
    IP: 127.0.0.1

### AGENTS ###
agent:
  config:
    COUNTRY_NAME: US
    STATE_NAME: MA
    LOCALITY_NAME: Boston
    ORG_NAME: saga
